# Florian template selection message
geometry_msgs/PoseStamped  pose
std_msgs/UInt8             template_id
std_msgs/UInt8             template_type
std_msgs/Int8              confidence
geometry_msgs/PoseStamped  hand_offset
geometry_msgs/Point        com
std_msgs/Float32           mass
geometry_msgs/Point        bounding_max
geometry_msgs/Point        bounding_min
string                     mesh_path
